name: Telegram Pusher

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP File
        run: |
          ZIP_NAME="repo_snapshot.zip"
          git archive -o $ZIP_NAME HEAD
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Send ZIP
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          curl -F chat_id="-4738544022" \
               -F document=@"$ZIP_NAME" \
               -F caption="🚀 *New push to repository!*
          Repository: \`${{ github.repository }}\`
          Branch: \`${{ github.ref_name }}\`
          Commit: \`${{ github.event.head_commit.message }}\`
          " -F parse_mode="Markdown" \
          "https://api.telegram.org/bot$BOT_TOKEN/sendDocument"
